version: '3'

services:
  mongo_db:
    container_name: songs-db-mongo
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
      - '28017:28017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: songs-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    command: ["sh", "-c", "elasticsearch-plugin list | grep -q analysis-icu || (echo 'ICU plugin not found, installing...' && elasticsearch-plugin install analysis-icu && export ICU_PLUGIN_INSTALLED=true) && echo 'ICU plugin already installed' && exec elasticsearch"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host
  kibana:
    container_name: songs-kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - 5601:5601
